### ISSUE TITLE
java.util.ConcurrentModificationException at com.xiaojinzi.component.Component.check

### ISSUE THREAD

**Issue by RickyHal** [xiaojinzi123/Component#105]
复现场景：
```kotlin
Component.init(true, Config.with(this).build())
ModuleManager.getInstance().registerArr("**", "**", "***")
Component.check()
```
日志：
```Java
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1454)
    at java.util.HashMap$EntryIterator.next(HashMap.java:1488)
    at java.util.HashMap$EntryIterator.next(HashMap.java:1486)
    at com.xiaojinzi.component.impl.RouterCenter.check(RouterCenter.java:438)
    at com.xiaojinzi.component.Component.check(Component.java:205)
    ...
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588)
    at android.app.ActivityThread.access$2600(ActivityThread.java:260)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8668)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
应该是check的时候又在注册路由造成的，目前没有想到解决方案

**Comment by xiaojinzi123** [comment]
1. 这是一个以前版本已知的问题. 不影响线上, 因为文档中告知了 check() 方法在 debug 的时候帮助你检测的作用
2. 新的版本中没有这个问题了

**Comment by xiaojinzi123** [comment]
其实 check 只是一个辅助功能, 你可以去掉的. 不打紧
check 是帮助你注册的路由或者服务是否重名了. 可以去掉这个辅助功能

**Comment by RickyHal** [comment]
> 其实 check 只是一个辅助功能, 你可以去掉的. 不打紧 check 是帮助你注册的路由或者服务是否重名了. 可以去掉这个辅助功能

好的谢谢
