### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Catherinelhl** [xiaojinzi123/Component#29]
Caused by: java.lang.IllegalArgumentException: not a valid name: 'component1ModuleApplicationGeneratedDefault
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:413)
	at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:392)
	at com.squareup.javapoet.TypeSpec.classBuilder(TypeSpec.java:112)
	at com.xiaojinzi.component.ModuleAppProcessor.createImpl(ModuleAppProcessor.java:118)
	at com.xiaojinzi.component.ModuleAppProcessor.init(ModuleAppProcessor.java:57)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
	at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.init(NonIncrementalProcessor.java:33)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$301(TimeTrackingProcessor.java:37)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$4.create(TimeTrackingProcessor.java:88)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$4.create(TimeTrackingProcessor.java:85)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.init(TimeTrackingProcessor.java:85)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)

**Comment by xiaojinzi123** [comment]
分支切换到 master 或者 master-androidx 就好了. develop 是最新的开发分支
