### ISSUE TITLE
最新版本无法编译通过

### ISSUE THREAD

**Issue by pengbs** [xiaojinzi123/Component#32]
版本：1.7.6
gradle编译日志：
Caused by: java.lang.NullPointerException: element == null
	at com.squareup.javapoet.Util.checkNotNull(Util.java:57)
	at com.squareup.javapoet.ClassName.get(ClassName.java:207)
	at com.xiaojinzi.component.ServiceProcessor.init(ServiceProcessor.java:58)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)

**Comment by xiaojinzi123** [comment]
> 版本：1.7.6
> gradle编译日志：
> Caused by: java.lang.NullPointerException: element == null
> at com.squareup.javapoet.Util.checkNotNull(Util.java:57)
> at com.squareup.javapoet.ClassName.get(ClassName.java:207)
> at com.xiaojinzi.component.ServiceProcessor.init(ServiceProcessor.java:58)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.(JavacProcessingEnvironment.java:500)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
> at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
> at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
> at com.sun.tools.javac.main.Main.compile(Main.java:523)

你这个应该不是啥问题, 你加群, 方便我查看你的问题. 问题解决了我会在这里结束这个 issue 的

**Comment by xiaojinzi123** [comment]
> 版本：1.7.6
> gradle编译日志：
> Caused by: java.lang.NullPointerException: element == null
> at com.squareup.javapoet.Util.checkNotNull(Util.java:57)
> at com.squareup.javapoet.ClassName.get(ClassName.java:207)
> at com.xiaojinzi.component.ServiceProcessor.init(ServiceProcessor.java:58)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.(JavacProcessingEnvironment.java:500)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
> at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
> at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
> at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
> at com.sun.tools.javac.main.Main.compile(Main.java:523)

我怎么感觉是你对应的 module 没有引入依赖呀.
请确保你是按照我的指引进行的配置！

[配置](https://github.com/xiaojinzi123/Component/wiki/%E4%B8%BB%E9%A1%B5)

**Comment by pengbs** [comment]
确实是配置问题，我从1.7.4升级到1.7.6， 有个module里面没改

**Comment by xiaojinzi123** [comment]
> 确实是配置问题，我从1.7.4升级到1.7.6， 有个module里面没改

感谢你一直以来的使用, 谢谢. 如果有兴趣可以加入我的群. 解决你的问题会更加的快速
